# Generated by Django 5.0.4 on 2024-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCMarket', '0002_alter_product_seller_delete_hcuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
